-- 학생테이블 생성
CREATE TABLE STUDENT(
    NO NUMBER(2) NOT NULL,
    SD_NUM NUMBER(8) NOT NULL,
    SD_NAME VARCHAR2(12) NOT NULL,
    SD_ID VARCHAR2(10) NOT NULL,
    SD_PASSWD VARCHAR2(20) NOT NULL,
    S_NUM CHAR(2) NOT NULL,
    SD_BIRTH VARCHAR2(20) NOT NULL,
    SD_ADDRESS VARCHAR2(20 CHAR) NOT NULL,
    SD_EMAIL VARCHAR2(30) NOT NULL,
    SD_DATE DATE NOT NULL,
    CONSTRAINT STUDENT_NO_UK UNIQUE(NO)
);
INSERT INTO STUDENT
VALUES(1, 06010001, '김정수', 'javajsp', '1234', 01, '19920514'

-- 과목테이블 생성
CREATE TABLE LESSON(
    NO NUMBER(2) NOT NULL,
    L_ABBRE VARCHAR2(20) NOT NULL,
    L_NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT LESSON_NO_UK UNIQUE(NO)
);

-- 학과테이블 생성
CREATE TABLE SUBJECT(
    NO NUMBER(2) NOT NULL,
    S_NUM CHAR(2) NOT NULL,
    S_NAME VARCHAR2(20) NOT NULL
    CONSTRAINT SUBJECT_S_NUM_FK FOREIGN KEY(S_NUM) REFERENCES STUDENT(S_NUM)
);

-- 수강테이블 생성
CREATE TABLE TRAINEE(
    NO NUMBER(2) PRIMARY KEY,
    SD_NUM NUMBER(8) NOT NULL,
    L_ABBRE VARCHAR2(20) NOT NULL,
    T_SECTION VARCHAR2(10) CHECK(T_SECTION IN('CULTURE','MAJOR','MINOR')),
    T_DATE DATE SYSDATE
    CONSTRAINT TRAINEE_SD_NUM_FK FOREIGN KEY(SD_NUM) REFERENCES STUDENT(SD_NUM), 
    CONSTRAINT TRAINEE_L_ABBRE_FK FOREIGN KEY(L_ABBRE) REFERENCES SUBJECT(L_ABBRE)
);